/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai4;

import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.security.AlgorithmParameterGenerator;
import java.security.AlgorithmParameters;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PublicKey;
import java.security.spec.X509EncodedKeySpec;
import javax.crypto.Cipher;
import javax.crypto.KeyAgreement;
import javax.crypto.SecretKey;
import javax.crypto.spec.DHParameterSpec;

/**
 *
 * @author tanng
 */
public class Alice extends javax.swing.JFrame {

    KeyAgreement aliceKeyAgree;
    PublicKey bobPubKey;
    SecretKey aliceDesKey;
    Cipher AliceCipher;
    /**
     * Creates new form Alice
     */
    public Alice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtkhoaa = new javax.swing.JTextField();
        txtkhoab = new javax.swing.JTextField();
        txtkhoachung = new javax.swing.JTextField();
        txtmahoakab = new javax.swing.JTextField();
        btnTaoKhoaA = new javax.swing.JButton();
        btnHienThiKB = new javax.swing.JButton();
        btnkhoaAB = new javax.swing.JButton();
        btnMaHoaKAB = new javax.swing.JButton();
        btnMaHoaGiaiMa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Alice");

        jLabel2.setText("Khóa Alice");

        jLabel3.setText("Khóa BoB");

        jLabel4.setText("Khóa KAB");

        jLabel5.setText("Mã Hóa KAB");

        btnTaoKhoaA.setText("Tạo Khóa A");
        btnTaoKhoaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoKhoaAActionPerformed(evt);
            }
        });

        btnHienThiKB.setText("Hiển Thị KB");
        btnHienThiKB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiKBActionPerformed(evt);
            }
        });

        btnkhoaAB.setText("Khóa Chung");
        btnkhoaAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhoaABActionPerformed(evt);
            }
        });

        btnMaHoaKAB.setText("Mã Hóa KAB");
        btnMaHoaKAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaHoaKABActionPerformed(evt);
            }
        });

        btnMaHoaGiaiMa.setText("Mã Hóa/Giải Mã");
        btnMaHoaGiaiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaHoaGiaiMaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMaHoaGiaiMa)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtkhoaa)
                                    .addComponent(txtkhoab)
                                    .addComponent(txtkhoachung)
                                    .addComponent(txtmahoakab, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTaoKhoaA)
                                    .addComponent(btnHienThiKB)
                                    .addComponent(btnkhoaAB)
                                    .addComponent(btnMaHoaKAB))))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtkhoaa)
                        .addComponent(btnTaoKhoaA)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtkhoab)
                        .addComponent(btnHienThiKB)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtkhoachung)
                        .addComponent(btnkhoaAB)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmahoakab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMaHoaKAB))
                .addGap(18, 18, 18)
                .addComponent(btnMaHoaGiaiMa)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaoKhoaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoKhoaAActionPerformed
        try {
            AlgorithmParameterGenerator paramGen = AlgorithmParameterGenerator.getInstance("DH");
            paramGen.init(512);
            AlgorithmParameters params = paramGen.generateParameters();
            DHParameterSpec dhSkipParamSpec = 
                    (DHParameterSpec) params.getParameterSpec(DHParameterSpec.class);
            
            System.out.println("Generating a DH KeyPair...");
            KeyPairGenerator aliceKpairGen = KeyPairGenerator.getInstance("DH");
            aliceKpairGen.initialize(dhSkipParamSpec);
            KeyPair aliceKpair = aliceKpairGen.generateKeyPair();
            
            System.out.println("Initializing the KeyAgreement Engine with DH private key");
            aliceKeyAgree = KeyAgreement.getInstance("DH");
            aliceKeyAgree.init(aliceKpair.getPrivate());
            
            byte[] alicePubKeyEnc = aliceKpair.getPublic().getEncoded();
            FileOutputStream fos = new FileOutputStream("D:/A.pub");
            fos.write(alicePubKeyEnc);
            fos.close();
            txtkhoaa.setText(alicePubKeyEnc.toString());
            
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btnTaoKhoaAActionPerformed

    private void btnHienThiKBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiKBActionPerformed
        try {
            FileInputStream fis = new FileInputStream("D:/B.pub");
            byte[] bkeyP = new byte[fis.available()];
            fis.read(bkeyP);
            fis.close();
            txtkhoab.setText(bkeyP.toString());
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHienThiKBActionPerformed

    private void btnkhoaABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhoaABActionPerformed
        try {
            FileInputStream fis = new FileInputStream("D:/B.pub");
            byte[] bobPubKeyEnc = new byte[fis.available()];
            fis.read(bobPubKeyEnc);
            fis.close();
            
            KeyFactory aliceKeyFac = KeyFactory.getInstance("DH");
            X509EncodedKeySpec x509KeySpec = new X509EncodedKeySpec(bobPubKeyEnc);
            bobPubKey = aliceKeyFac.generatePublic(x509KeySpec);
            System.out.println("Executing PHASE1 of key agreement...");
            aliceKeyAgree.doPhase(bobPubKey, true);
            byte[] aliceSharedSecret = aliceKeyAgree.generateSecret();
            
            System.out.println("Khoa chung: secret (DEBUG ONLY): " + CryptoUtil.toHexString(aliceSharedSecret));
            txtkhoachung.setText(CryptoUtil.toHexString(aliceSharedSecret));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnkhoaABActionPerformed

    private void btnMaHoaKABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaHoaKABActionPerformed
        try {
            aliceKeyAgree.doPhase(bobPubKey, true);
            aliceDesKey = aliceKeyAgree.generateSecret("DES");
            txtmahoakab.setText(aliceDesKey.toString());
            
            BufferedWriter bw = null;
            String fileName = "D:\\KhoaA.txt";
            bw = new 
                BufferedWriter(new FileWriter(fileName));
            bw.write(aliceDesKey.toString());
            bw.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnMaHoaKABActionPerformed

    private void btnMaHoaGiaiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaHoaGiaiMaActionPerformed
        DESCS des = new DESCS();
        des.setVisible(true);
    }//GEN-LAST:event_btnMaHoaGiaiMaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHienThiKB;
    private javax.swing.JButton btnMaHoaGiaiMa;
    private javax.swing.JButton btnMaHoaKAB;
    private javax.swing.JButton btnTaoKhoaA;
    private javax.swing.JButton btnkhoaAB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtkhoaa;
    private javax.swing.JTextField txtkhoab;
    private javax.swing.JTextField txtkhoachung;
    private javax.swing.JTextField txtmahoakab;
    // End of variables declaration//GEN-END:variables
}
